server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/vietthong812/ecommerce_config_repo.git
          username: vietthong812
          password: ${GIT_PASSWORD}
          default-label: main
          search-paths: config_repo
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
